### ISSUE TITLE
指示样式

### ISSUE THREAD

**Issue by yueduz** [HollowMan6/Customize-IBus#4]
![2021-05-08 19-04-41 的屏幕截图](https://user-images.githubusercontent.com/1448159/117536910-5c656600-b030-11eb-8c42-e8def7032c8f.png)
![2021-05-08 19-06-16 的屏幕截图](https://user-images.githubusercontent.com/1448159/117536937-83239c80-b030-11eb-85e3-2afde6e14fbd.png)
以前的palm webos 输入法是这样指示的,alt按下时是绿点,alt锁定时是黑点,shift按下时是绿上向上箭头,shfit锁定时是黑色向上箭头.

使用一个小点提示能减少对文字的遮盖,所以webos上只要锁定了就一直有指示图标,不会超时隐藏,我觉得这体验非常好,至今仍无超越.

在电脑上,可以用来提示大小写锁定状态.数字键锁定状态.

关于输入法分指示,我认为是中文输入法就不要指示了,没有指示就是中文输入法.如果中文输入法也指示的话就和输入法本来的候选有点冲突.

中文输入法从不指示,英文输入法一直指示,我认为这是最好的.当需要临时隐藏指示时就通过切换到中文输入法来隐藏.

错误报告:
       当前我多切换了几次后,切换到英文后指示的文字也是中文的.

**Comment by HollowMan6** [comment]
> 以前的palm webos 输入法是这样指示的,alt按下时是绿点,alt锁定时是黑点,shift按下时是绿上向上箭头,shfit锁定时是黑色向上箭头.
> 
> 使用一个小点提示能减少对文字的遮盖,所以webos上只要锁定了就一直有指示图标,不会超时隐藏,我觉得这体验非常好,至今仍无超越.
> 

目前我的插件输入法提示小框是直接使用BoxPointer做的，https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/boxpointer.js ，如果做成小点这种形式需要自己写图形类，比较麻烦，暂时无计划这样做。

> 在电脑上,可以用来提示大小写锁定状态.数字键锁定状态.
> 

另外，目前识别中文英文输入法切换是通过IBus事件触发接口实现的：https://github.com/HollowMan6/Customize-IBus/blob/main/customize-ibus%40hollowman.ml/extension.js#L187-L192 如果是提示大小写锁定和数字键锁定，还没找到相关接口，后续我将继续看看有没有相关接口，如果没有的话可能需要上游支持，GNOME相关事件接口或者IBus相关事件接口支持，否则采用轮询的话性能太差。

> 关于输入法分指示,我认为是中文输入法就不要指示了,没有指示就是中文输入法.如果中文输入法也指示的话就和输入法本来的候选有点冲突.
> 中文输入法从不指示,英文输入法一直指示,我认为这是最好的.当需要临时隐藏指示时就通过切换到中文输入法来隐藏.
> 

好的，后续可以添加配置选项支持隐藏切换到除英文外其它语言的提示。另外支持设定取消自动隐藏。

> 错误报告:
> 当前我多切换了几次后,切换到英文后指示的文字也是中文的.

这个应该是此原因导致的，已经提交了补丁，新版本会修复：https://github.com/HollowMan6/Customize-IBus/commit/6e91666ef06519ba321f7e7506ef1261e72b3b5c 目前我这里在这个补丁作用之后没有遇到这个错误，后续会继续观察。

**Comment by yueduz** [comment]
实际上因为这个问题，我已经转而使用fcitx5了。https://github.com/libpinyin/ibus-libpinyin/issues/222。
我使用码表输入法，我觉得fcitx5的码表引擎比rime都灵活。

**Comment by HollowMan6** [comment]
v39(GNOME 3.38)和v40(GNOME 40)已经发布了，等待应用商店审核中。
> 关于输入法分指示,我认为是中文输入法就不要指示了,没有指示就是中文输入法.如果中文输入法也指示的话就和输入法本来的候选有点冲突.
> 中文输入法从不指示,英文输入法一直指示,我认为这是最好的.当需要临时隐藏指示时就通过切换到中文输入法来隐藏.
> 
这样配置即可实现该需求：
![image](https://user-images.githubusercontent.com/43995067/117548544-2e037d00-b068-11eb-92e2-ee70c9815ef2.png)

示意：
![Peek 2021-05-08 22-28](https://user-images.githubusercontent.com/43995067/117548632-9a7e7c00-b068-11eb-9e96-bb72042239da.gif)

**Comment by HollowMan6** [comment]
> 实际上因为这个问题，我已经转而使用fcitx5了。[libpinyin/ibus-libpinyin#222](https://github.com/libpinyin/ibus-libpinyin/issues/222)
> 
> 即使帖子结尾说已经实现了这个功能，但是我刚刚装了archlinux源里的最新版还是没跟随在我想要的位置。

这个的话似乎我注意到火狐浏览器上是你要求的位置，可以见上面动图。其它的我测试了gedit等，似乎还是跟随光标移动的。目前GNOME Shell插件是不能自定义这个的，因为设定候选框位置的相关事件引发的操作已经写死，必须到上游去改，很遗憾帮不到你。

> 我使用码表输入法，我觉得fcitx5的码表引擎比rime都灵活。

我使用拼音输入，在我看来fcitx和ibus都挺好的。：）

**Comment by yueduz** [comment]
> > 实际上因为这个问题，我已经转而使用fcitx5了。[libpinyin/ibus-libpinyin#222](https://github.com/libpinyin/ibus-libpinyin/issues/222)
> > 即使帖子结尾说已经实现了这个功能，但是我刚刚装了archlinux源里的最新版还是没跟随在我想要的位置。
> 
> 这个的话似乎我注意到火狐浏览器上是你要求的位置，可以见上面动图。其它的我测试了gedit等，似乎还是跟随光标移动的。目前GNOME Shell插件是不能自定义这个的，因为设定候选框位置的相关事件引发的操作已经写死，必须到上游去改，很遗憾帮不到你。
> 
> > 我使用码表输入法，我觉得fcitx5的码表引擎比rime都灵活。
> 
> 我使用拼音输入，在我看来fcitx和ibus都挺好的。：）

fcitx5在任何程序中都跟在我要的位置

**Comment by HollowMan6** [comment]
> fcitx5在任何程序中都跟在我要的位置。

如果你还想继续使用IBus的话，建议你继续在你上面提到的Issue https://github.com/libpinyin/ibus-libpinyin/issues/222 跟进反馈。

> 而且我看你的动图，每键入一个字母候选框都要抖一下，最受不了这种。

你指的是上下抖动吗？这是我插件最新引入的https://github.com/HollowMan6/Customize-IBus#%E5%8A%A8%E7%94%BB 动画功能，我开启了滑动动画。默认是关闭的，我倒是对这样的没有特别的感受：）

**Comment by HollowMan6** [comment]
> 在电脑上,可以用来提示大小写锁定状态.数字键锁定状态.

找到了一个提示大小写锁定状态.数字键锁定状态的插件，还是挺好用的，可以试试看：https://extensions.gnome.org/extension/36/lock-keys/

**Comment by HollowMan6** [comment]
> 
> fcitx5在任何程序中都跟在我要的位置。

我刚刚又研究了一下，发现了这个commit：https://github.com/libpinyin/ibus-libpinyin/commit/330ba5b289eec7670aa82244ed9064d8bc6d537b ，然后结合评论：
https://github.com/libpinyin/ibus-libpinyin/issues/222#issuecomment-599374918 ，现在ibus-libpinyin里确实是实现了你要的位置，只要点击libpinyin的首选项，然后设置显示风格为压缩就是你想要的位置了！
![图片](https://user-images.githubusercontent.com/43995067/117559639-90389e00-b0b9-11eb-91a8-f78b6bac8b13.png)
![图片](https://user-images.githubusercontent.com/43995067/117559696-1fde4c80-b0ba-11eb-8329-e738646c555c.png)

因为你使用的是码表输入法，我不知道ibus-rime和ibus-table的情况，但是既然ibus-libpinyin可以实现，你也可以向这两个社区要求这个功能：）

**Comment by yueduz** [comment]
我已经向ibus-rime提了请求
谢谢

Hollow Man ***@***.***>于2021年5月9日 周日11:33写道：
