### ISSUE TITLE
About the vicious slander made by @shenlebantongying

### ISSUE THREAD

**Issue by HollowMan6** [HollowMan6/Customize-IBus#5]
https://github.com/tuberry/ibus-tweaker/issues/15#issue-896029263

I have seen the comments by the ignorant and prejudiced @shenlebantongying . He has a lot of misundertandings about my project, but instead of commenting on my project issue first, he went to one of the project that this project refers to and made bullshits. And moreover, he blocks me, even before I have any chance to say anything and make any self-defense.

![image](https://user-images.githubusercontent.com/43995067/118927729-cbb65080-b974-11eb-9fa1-56c49131fd9d.png)

You can see that in the page below it doesn't have a `follow` button, which means he blocks me.

![image](https://user-images.githubusercontent.com/43995067/118928446-d02f3900-b975-11eb-9b9e-3752f280b34c.png)

What he said is definitely fake and a vicious slander to me.

Could @shenlebantongying actually see the commit history that I have made until today to check if I really just purely "copied" from others?

![image](https://user-images.githubusercontent.com/43995067/118928851-5ea3ba80-b976-11eb-8a84-f50407360557.png)

> If he is truly a free software user/contributor, he could just contribute to your repo or collaborate with you. He simply copy a few projects into one, so that he can put another "project" on his résumé.

Since @tuberry is not my mentor at IBus at GSoC, I can't collaborate with him as Google needs applicants to do the project alone with the help of mentors. I admit that some of the basic ideas are from tuberry, and I have made the necessary acknowledgement: https://github.com/IBus-Customize/Customize-IBus/tree/main#%E8%87%B4%E8%B0%A2 to @tuberry 's project, even including the headers: https://github.com/HollowMan6/Customize-IBus/blob/main/customize-ibus%40hollowman.ml/extension.js#L3 . And moreover what do you mean by copying a few projects into one? @tuberry acknowledges the https://github.com/tuberry/ibus-tweaker#acknowledgements ibus-font-setting which is done by my mentor @epico , so I acknowledge that too. And I acknowledge background-logo since I didn't know how to realize choosing a picture in GTK at that time and background-logo gave me the idea. Other features are all done by myself alone.

The required feature https://github.com/openSUSE/mentoring/issues/158 by GSoC project customized pre-edit themes is definitely done by myself alone since @tuberry only place those css styles in extension's css files, not the random user-selected stylesheet.
Only five days later had I made the demo that fit the GSoC project required feature which means users can freely choose the GNOME-Shell theme IBus style they need. So in a conclusion the function require by the GSoC project has nothing to do with @tuberry and is all done by myself alone. https://github.com/IBus-Customize/Customize-IBus/commit/b8e54a4543ba1abc62365345396d37712aa93f5f

More details can be found on my proposal for GSoC about how I discovered the way to extract GNOME-Shell Theme and realized customized pre-edit themes: https://github.com/HollowMan6/My-Google-Summer-of-Code/blob/main/2020-OpenSUSE/Proposal.pdf

> but I feel a bit disgusted for this type of "rearrange a few buttons, then it is MY project" kind of shits

That's totally bullshit. Can you compare the features realized by @tuberry's extension:

```
Tweaker of ibus for orientation, theme, font and ascii mode auto-switch.
```

And mine? It's "rearrange a few buttons, then it is MY project" ??? You are really so ignorant, @shenlebantongying

```
Customize IBus for orientation, animation, font, ascii mode auto-switch, reposition, system tray menu entries, input source indicator; theme and background picture follow GNOME Night Light Mode.
```

>  (like many made-in-china "open source" which are just renaming open source projects with little alternation. It is a corrupted culture.)

That's another prejudice against Chinese Open Source. Are you a racist?
 
> and I don't think he will do anything about the project after GSoC ends.

Well, it seems our little @shenlebantongying knows everything, really? That's really ignorant. How do you know if I won't do anything about the project? If I just want to finish the project and get the money, why would I spend time writing code for animation, reposition, system tray menu entries, input source indicator; theme and background picture follow GNOME Night Light Mode? Why don't I just do the required feature by GSoC to only let users customize IBus with GNOME-Shell themes https://github.com/openSUSE/mentoring/issues/158 ? This is purely a vicious slander.

> I think you may consider copying some functionality back since both are GPL-ed.

That's OK, if @tuberry wants to do so.

> It is still the same software but with some customization copied from some other projects

??? Are you sure? What kind of project??? Give me an example?

![image](https://user-images.githubusercontent.com/43995067/118936156-dd9cf100-b97e-11eb-8c69-5357148230d7.png)

I can copy from nowhere.

>  (and renaming variables to increase "commit number" and SLOC like his other projects).

??? That's another bullshit and a vicious slander. Give me an example??? You are talking shits without an example.

And also some of replies to @tuberry who is misguided by @shenlebantongying:

> Adding background images under high-frequency changing text is distracting and confusing. It could be better to use border-image instead of background-image

Some users may like some background pictures, that include me.

> In fact, if users want to write css files to customize them, I'd like to recommend another extension — user-theme-x.

Actually this extension is only a part of my project for GSoC, you can check https://github.com/IBus-Customize/IBus-Theme-Tools for extracting GNOME-Shell IBus styles to generate a stylesheet in details. Your user-theme-x is limited.

> I have implemented the input method indicator, but the effect is not good enough to reach the degree of fcitx5, that may need ibus upstream to improve the input context event mechanism. Maybe I will look into it later.

You have implemented? I don't see the source code. My input method indicator is nice and gets a positive feedback. See here: https://github.com/HollowMan6/Customize-IBus/issues/4

> The pop-up animation seems to me to be a waste of tens or hundreds of milliseconds to see the results.

Why I want to implement this feature is that I see a feature request in here: https://github.com/tuberry/ibus-tweaker/issues/10 . You just ignore users' need and talk about its disadvantage here?

> I'm not sure about the use case of drag & drop. I remember a kind of problem of linux input method is that the candidate box does not follow the cursor, is this to let the user manually make it follow? If so, that's not much of a user-friendly workaround.

That's a feature realized by Sougou Pinyin on Windows. You misunderstand my feature. I guess you actually haven't tried my extension? How can you just directly make comments?

https://github.com/IBus-Customize/Customize-IBus#%E6%8B%96%E6%8B%BD%E7%A7%BB%E5%8A%A8

> For the rest, the added menu items are almost useless to me.

These menu entry items are all in the menu of the IBus status indicator in Non-GNOME desktop. I just want users who used to use Non-GNOME desktop like KDE and then switch to GNOME to find it familiar. If it's useless to you, that's fine.

> Of course the above are my own humble opinions, if there are any features you would like to see in a few of them or if you have any other suggestions, please open another issue so that we can discuss them.

If you would like to work further on this project with me, I can add you as a maintainer after GSoC ends. But not now since it's Google's rule.

This is totally a waste of time for me to reply to ignorant @shenlebantongying , I will report to GitHub about the vicious slander make by @shenlebantongying to me afterwards.

**Comment by HollowMan6** [comment]
@shenlebantongying Have reported to GitHub about this intentionally vicious slander.
![image](https://user-images.githubusercontent.com/43995067/118943215-ff4da680-b985-11eb-90f7-0290fbca9b82.png)

**Comment by tuberry** [comment]
I don't want to get involved in your argument, nor do I want to be a peacemaker, but I hope you will delete this issue as you promised, after all, the quoted content no longer exists.

**Comment by HollowMan6** [comment]
> I don't want to get involved in your argument, nor do I want to be a peacemaker, but I hope you will delete this issue as you promised, after all, the quoted content no longer exists.

Ok，Fairly enough.
